language: ruby
sudo: false
dist: trusty
rvm:
  - 2.5.0
branches:
  only:
  - master
addons:
  apt:
    packages:
    - lftp
    - texlive-extra-utils
    - imagemagick
    - ghostscript
    - poppler-utils
env:
  global:
  - JEKYLL_ENV=production
script:
  - npm install -g bower
  - bower install
  - gem install bundler
  - bundle exec jekyll build
after_success:
  - echo set ftp:ssl-force on > ~/.lftprc
  - echo set ftp:ssl-protect-data on >> ~/.lftprc
  - echo set ssl:verify-certificate no >> ~/.lftprc
  - lftp -u "mobihoc2019@sigmobile.hosting.acm.org,$PASSWORD" ftp.sigmobile.hosting.acm.org -e "mirror --delete --delete-first --verbose -R _site/ .; bye" || true
