safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '.asset-cache', '.travis.d']

plugins:
  - jekyll-assets
  - jekyll-last-modified-at
  - jekyll-sitemap

title: "MobiHoc 2023"
description: "MobiHoc 2023, the 24th International Symposium on Mobile Ad Hoc Networking and Computing, will focus on the latest research in the rapidly growing area of mobile ad hoc networking and computing. This symposium will be held in Washington DC, USA, in October 2023."

# baseurl: "/mobihoc/2019"
baseurl: "/mobihoc/2023"
url: "https://www.sigmobile.org"

google:
  - analytics: UA-83529610-3

## Note. Uncomment and update spreadsheet parameters to enable pulling program
##       data from Google Sheet(s)

#   # If the specified file doesn't exist, there will be command-line dialog to create it
#   # (Currently hardcoded for a dummy robot.mcrobot.jr@gmail.com account permissions)
#keynote:
#  google_client_id: .travis.d/google_client_id.json
#   # Google spreadsheet with the conference data
#  spreadsheet:
#    - "1wPsGgoY2KBHr9NECwPbB9RnnVMAue5WXI-CwkI0mevU" # main

program:
  google_client_id: .travis.d/google_client_id.json
#   # Google spreadsheet with the conference data
  spreadsheet:
    - "1qzsK27dGioaDXXW0BElQiROY2E4cOf9pxAr32tbPEnw" # main

assets:
  caching:
    path: .sass-cache/assets
  features:
    automatic_img_size: false

  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/files
    - .sass-cache

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
